# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

use_frameworks!

def testing_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'QuickNimbleProject' do
	
end

target 'QuickNimbleProjectTests' do
	testing_pods
end

target 'QuickNimbleProjectUITests' do
	testing_pods
end

