# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
# Uncomment this line if you're using Swift
platform :ios, '9.0'

use_frameworks!

target 'QuickNimbleProject' do

end

target 'QuickNimbleProjectTests' do
	pod 'Quick'
	pod 'Nimble'
	pod 'OCMock'
end

target 'QuickNimbleProjectUITests' do
	pod 'Quick'
	pod 'Nimble'
	pod 'OCMock'
end

